### ISSUE TITLE
CPF - Converted PQ buses have 0 QG

### ISSUE THREAD

**Issue by ElisNycander** [MATPOWER/matpower#15] opened 2017-05-31 15:12 UTC
Generator 5 is at its minimum Q-limit already in the base case of the CPF. Since Qlimits are enforced it is converted to a PQ bus. However, in the target case the Q value has been set to 0 instead of the limit that was reached in the base case. This is due to line 272 and 284 in runcpf, where only the Q-values for active generators are copied to the target case.

Base case:

```
================================================================================
|     Generator Data                                                           |
================================================================================
 Gen   Bus   Status     Pg        Qg   
  #     #              (MW)     (MVAr) 
----  -----  ------  --------  --------
  1      1      1      40.00     56.55
  2      1      1     170.00    -40.87
  3      3      1     323.49    194.65
  4      4      1       5.02    180.86
  5      5      1     466.51    -20.00
                     --------  --------
            Total:   1005.02    371.20
```

Target case:
```
================================================================================
|     Generator Data                                                           |
================================================================================
 Gen   Bus   Status     Pg        Qg   
  #     #              (MW)     (MVAr) 
----  -----  ------  --------  --------
  1      1      1     432.12   2311.84
  2      1      1    1836.52   2216.62
  3      3      1    3494.68   5093.80
  4      4      1    1049.50   4240.78
  5      5      1    5039.74      0.00
                     --------  --------
            Total:  11852.56  13863.04
```

Code:
```
clear; 
close all;

define_constants;

%% options

mpopt  =  mpoption('out.all',  -1,  'verbose',  2);

mpopt = mpoption(mpopt, 'out.sys_sum', 1,  ...
                        'out.area_sum', 0, ...
                        'out.bus', 1, ...
                        'out.branch', 0, ...
                        'out.gen', 1, ...
                        'out.force', 0 );

% pf options
mpopt = mpoption(mpopt, 'pf.nr.max_it', 20);
mpopt = mpoption(mpopt, 'pf.enforce_q_lims', 1);

% cpf options
mpopt = mpoption(mpopt, 'cpf.stop_at', 'NOSE', 'cpf.step', 1); 
mpopt = mpoption(mpopt, 'cpf.plot.level', 2);
mpopt = mpoption(mpopt, 'cpf.plot.bus', 2);
mpopt = mpoption(mpopt, 'cpf.parameterization', 2);
mpopt = mpoption(mpopt, 'cpf.enforce_q_lims',1);
mpopt = mpoption(mpopt, 'cpf.adapt_step',1);


mpcbase = case5;

% switch limits to make generator at bus 5 reach Qmax but not generator at
% slack bus
mpcbase.gen(:,QMAX) = 1e5;
mpcbase.gen(5,[QMAX QMIN]) = [20 -20];

runpf(mpcbase,mpopt);

% target case: increase load and generation 
mpctarget = mpcbase;
mpctarget.bus(:,[PD QD]) = mpctarget.bus(:,[PD QD])*2;
mpctarget.gen(:,[PG QG]) = mpctarget.gen(:,[PG QG])*2;

runcpf(mpcbase,mpctarget,mpopt);
```

Version:
```
MATPOWER               Version 6.0        16-Dec-2016
MATLAB                 Version 8.6        13-Aug-2015   Release: (R2015b)  
Optimization Toolbox   Version 7.3        13-Aug-2015   Release: (R2015b)  
MIPS                   Version 1.2.2      16-Dec-2016
MOST                   Version 1.0        16-Dec-2016
SDP_PF                 -- not installed --
YALMIP                 -- not installed --
BPMPD_MEX              -- not installed --
CLP                    -- not installed --
CPLEX                  -- not installed --
GLPK                   -- not installed --
Gurobi                 -- not installed --
IPOPT                  -- not installed --
KNITRO                 -- not installed --
MINOPF                 -- not installed --
MOSEK                  -- not installed --
PARDISO                -- not installed --
PDIPMOPF               -- not installed --
SCPDIPMOPF             -- not installed --
SDPT3                  -- not installed --
SeDuMi                 -- not installed --
TRALMOPF               -- not installed --
Architecture:          PCWIN64

  MATPOWER 6.0 is distributed under the 3-clause BSD License.
  Please see the LICENSE file for details.
```

**Comment by rdzman** [comment] 2017-05-31 18:55
Sorry for my bad memory. I should have recognized this as a duplicate of issue #4, which was reported and fixed a few months ago. So the current [`master` branch](https://github.com/MATPOWER/matpower) should already contain the fix.

It's always a good idea to make sure you can reproduce the issue with the latest `master` (see step 2 in [Reporting a Bug](https://github.com/MATPOWER/matpower/blob/master/CONTRIBUTING.md#reporting-a-bug)).

But thanks for taking the time and effort to report.

**Closed** 2017-05-31 18:55 UTC
Labels: duplicate
